apiVersion: apps/v1
kind: Deployment
metadata:
  name: aws-dissembler
spec:
  replicas: 1
  selector:
    matchLabels:
      name: aws-dissembler
  template:
    metadata:
      labels:
        name: aws-dissembler
    spec:
      serviceAccountName: aws-dissembler
      containers:
        - name: aws-dissembler
          # Replace this with the built image name
          image: REPLACE_IMAGE
          ports:
          - containerPort: 60000
            name: metrics
          command:
          - aws-dissembler
          imagePullPolicy: Always
          readinessProbe:
            exec:
              command:
                - stat
                - /tmp/operator-sdk-ready
            initialDelaySeconds: 4
            periodSeconds: 10
            failureThreshold: 1
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "aws-dissembler"
